export const SUCCESS        = 'SUCCESS'
export const FAILURE        = 'FAILURE'
export const PENDING_ACTIVE = 'PENDING_ACTIVE'
export const PENDING_IDLE   = 'PENDING_IDLE'
export const EXISTING       = 'EXISTING'
